### PR TITLE
doc: add project setup

### PR DESCRIPTION
**Pull request by johnchen383**
**Issue**
Improve clarity in setting up codebase

**Solution**
Specify .env-template file

### CODE REVIEW

**Comment by luorixo** [comment]
yes it looks good.

**Review by ardo715 — APPROVED** [review]
Looking good

**Review by luorixo — APPROVED** [review]
Ok this is good

**Comment by bcho892** [comment]
good

**Review by alexmingikim — COMMENTED** [review]
LGTM!

**Pull request merged**
