### PR TITLE
380 app login confirmation

### LINKED ISSUE #380: App: Log-In Confirmation
### Description:

As a student user,
I want to know I have logged in correctly,
So that I'm confident I'm sitting the right exam as the right person.

Add visual indication of who has signed in.

### Acceptance Criteria:
- [x] There is obvious visual indication of the user that has signed in.
- [x] Email changed*

### Definition of Done:
- [ ] AC met
- [ ] PR linked
- [ ] Branch merged

### Notes
I recommend a welcome message (including the name of the user) on the app page, but feel free to implement something else if you think it'll be better.
We won't have editable profiles.

\* Unrelated, but I figured I'd add it to this ticket. Change the email on the app page from `contact.nzpmc@gmail.com` to `contact@nzpmc.com`.

### PR DESCRIPTION
**Pull request by bcho892**
**Issue**

Closes #380 

**Solution**

image

image

I have displayed the user's name on the exams page as well as when they click the user icon on the navbar.

Additionally, I have corrected the contact email.
**Risks**
No risk

**Reviewers**

### CODE REVIEW

**Comment by bcho892** [comment]
**NOTE:** this assumes that the user has a displayName in firebase auth, if not, one will have to be set using the modified editUser mutation that I have created

FYI: @nzkevc

**Review by nzkevc — APPROVED** [review]

**Review by johnchen383 — CHANGES_REQUESTED** [review]
nit: can we enforce name casing on names.  i.e. regardless of how its stored in Firebase we capitalise first and last names.

**Comment by bcho892** [comment]
```ts
export default {
    methods: {
        nameCase(name: string | undefined | null) {
            if (!name) return ""
            const trimmedName = name.trim()
            const formattedName = trimmedName
                .toLowerCase()
                .split(' ')
                // Concats first letter capitalised and includes rest of string
                .map((substring: string) => substring.charAt(0).toUpperCase() + substring.substring(1))
                .join(' ')

            return formattedName
        },
    },
}
```

I've included this as a mixin to format the names, and this will be extensible to any other formatting that we may need.

**Comment by johnchen383** [comment]
> ```ts
> export default {
>     methods: {
>         nameCase(name: string | undefined | null) {
>             if (!name) return ""
>             const trimmedName = name.trim()
>             const formattedName = trimmedName
>                 .toLowerCase()
>                 .split(' ')
>                 // Concats first letter capitalised and includes rest of string
>                 .map((substring: string) => substring.charAt(0).toUpperCase() + substring.substring(1))
>                 .join(' ')
> 
>             return formattedName
>         },
>     },
> }
> ```
> 
> I've included this as a mixin to format the names, and this will be extensible to any other formatting that we may need.

Missing .toUpperCase() on last name?

**Comment by bcho892** [comment]
> > ```ts
> > export default {
> >     methods: {
> >         nameCase(name: string | undefined | null) {
> >             if (!name) return ""
> >             const trimmedName = name.trim()
> >             const formattedName = trimmedName
> >                 .toLowerCase()
> >                 .split(' ')
> >                 // Concats first letter capitalised and includes rest of string
> >                 .map((substring: string) => substring.charAt(0).toUpperCase() + substring.substring(1))
> >                 .join(' ')
> > 
> >             return formattedName
> >         },
> >     },
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've included this as a mixin to format the names, and this will be extensible to any other formatting that we may need.
> 
> Missing .toUpperCase() on last name?
```ts
                .split(' ')
                // Concats first letter capitalised and includes rest of string
                .map((substring: string) => substring.charAt(0).toUpperCase() + substring.substring(1))
```

The split separates the first and last name into an array, and the operation is performed on all names. 

Example:

john chen

1. `.split(' ')`
2. `['john', 'd']`
3. map (for each) -> john -> J + ohn & chen -> C + hen
4. We get `['John', 'Chen']`
5. Join gives us the string John Chen

**Review by johnchen383 — APPROVED** [review]
Perfect thanks for explaining haha

**Pull request merged**
