### PR TITLE
357 exam navbar

### LINKED ISSUE #357: Exam: Navbar
### Description:

Implement the navbar component for the exam page.
Builds on #352.

### Acceptance Criteria:
- [ ] Component created
- [ ] Functionality implemented (as much as possible in isolation)
- [ ] Unit tested
- [ ] Component embedded in index page (try to avoid merge conflicts by pulling regularly)

### Definition of Done:
- [ ] AC met
- [ ] PR linked
- [ ] Branch merged

### Notes
See Figma for design.
Remember that this component will eventually need to support an exam-editor version.

### PR DESCRIPTION
**Pull request by bcho892**
**Issue**

Closes #357 

**Solution**
image

The navbar has been implemented according to the figma design. Functionally it is correct, with it being blocked by issues: #359 and #361 

Functionality of the submit button, which is located in the navbar, is part of #361 therefore its implementation has been left incomplete in this PR.

**Risks**
Functionality such as flagging and answering a question has not been implemented yet so integration is not tested

**Reviewers**

### CODE REVIEW

**Review by luorixo — APPROVED** [review]
lgtm

**Review by luorixo — APPROVED** [review]
lgtm

**Review by johnchen383 — APPROVED** [review]

**Comment by Oculux314** [comment]
Love the styling and how it's responsive to different viewports!

Noting here for future reference:
- There's a bit of delay between when I click an answer to the navbar check icon showing up.
Is this just cause atm the navbar only checks firebase? When we move to prettifying things, we should try link up the navbar and answer panel directly.
- Also flagging requires two clicks rn for some reason.

**Comment by bcho892** [comment]
> Love the styling and how it's responsive to different viewports!
> 
> Noting here for future reference:
> 
> * There's a bit of delay between when I click an answer to the navbar check icon showing up.
>   Is this just cause atm the navbar only checks firebase? When we move to prettifying things, we should try link up the navbar and answer panel directly.
> * Also flagging requires two clicks rn for some reason.

Note that flagging is handled in #360, but yes I agree that there should be a synced way of updating the answer check.

**Pull request merged**
