### PR TITLE
316 implement auth page

### LINKED ISSUE #316: Implement New Designs: Auth
### Description:

Implement the new Auth design into the frontend.

### Acceptance Criteria:
- [ ] Before changes: confirm which designs are final
- [ ] Assets and Vuetify components decided on
- [ ] New designs implemented
- [ ] New webpage tested (just in browser is okay)

### Definition of Done:
- [ ] AC met
- [ ] Applicable tests written
- [ ] Applicable documentation in wiki
- [ ] PR reviewed
- [ ] Merged into main/feature branch
- [ ] Before vs After

### Notes / Links
Figma designs: https://www.figma.com/file/7gfY7pBsZyREkVODofWC8U/NZPMC-Screen-Redesigns?node-id=0-1

### PR DESCRIPTION
**Pull request by johnchen383**
**Issue**

Closes #316 

**Solution**

**Risk**

**Reviewers**

### CODE REVIEW

**Comment by Oculux314** [comment]
@johnchen383 Yo is this branch still relevant?

**Comment by alexmingikim** [comment]
Finally done!

**Issue**

Closes https://github.com/UoaWDCC/nzpmc-exam-portal/issues/316

**Solution**

- Removed sign up functionality 
- Replaced existing Vue text field components with new custom components
- Implemented and distinguished between different error messages
- Lot of style and design changes

**Risk**
None 

**Reviewers**
@Oculux314 
@luorixo

**Review by luorixo — APPROVED** [review]
Looks good! Checked it out and it is styled great

**Review by Oculux314 — APPROVED** [review]
Love the new, responsive design!
Eeven after a lot of edge case testing, couldn't find any bugs.
Tried out the forgot password functionality and it looks great and works well.

Amazing work!

**Comment by Oculux314** [comment]
Heads up I'll merge it tonight if you don't see it so we can show it off tomorrow :)

**Pull request merged**
