### PR TITLE
fix: got rid of the old styling, added functionality to new styling -…

### LINKED ISSUE #383: Admin: User Management Styling
### Description:

Finish implementing the design of the user management sub-page.

Blocks #384.

### Acceptance Criteria:
- [ ] User management sub-page design matches Figma.*

### Definition of Done:
- [ ] AC met
- [ ] PR linked
- [ ] Branch merged

### Notes
\* Ask Eugene or Nate if unsure.

### PR DESCRIPTION
**Pull request by luorixo**
**Issue**

Closes #383 

**Solution**

Got rid of the old styling, added functionality to the new styling. Everything should be working except for the 'Download all Users CSV button'

**Risks**

If my code is dodgy sorry :/

**Reviewers**
@Oculux314 
@ardo715

### CODE REVIEW

**Review by ardo715 — CHANGES_REQUESTED** [review]
The styling is looking good, however, as there are now 2 csv upload spots, we need to change this.currentCsv and split them into this.addCsv and this.deleteCsv. Right now I do not think the csvs are getting uploaded properly and the placeholder that had this.currentCsv I think is no longer being used

**Comment by Oculux314** [comment]
Hey Eugene trying to checkout your changes now but it returns with this error:
`git checkout 383_admin-user-mangement-styling`
`error: invalid path 'vUplo?OA?OA?OA?OA?OA?OA?OA?OA?OA?OA?OA?OA?OA?OB?OB?OB?OB?OB?OB?OB?OB?OB?OB?OB?OBqqq'`

I think it has to do with this corrupted file?
image
Could you try resetting and recommitting your latest changes?

**Review by ardo715 — APPROVED** [review]
LGTM, thank you for updating the csv attributes accordingly =)

**Review by Oculux314 — APPROVED** [review]
Looks good!

When testing it out I found I couldn't add, remove, or download csvs tho - will you create a new branch for #384?

**Review by Oculux314 — CHANGES_REQUESTED** [review]
Turns out I was just using the wrong csv format 🤦 
However I did notice that if you upload a csv, then modify it again then reupload it, it doesn't register the new csv.

Steps to reproduce:
- Download csv_dummy_template.csv from drive
- Click upload CSV to add users region (and select CSV)
- Click add users
- Modify CSV (e.g. change a user's name)
-  Click upload CSV to add users region again (select same CSV)
- Click add users --> no users added

Bit of a niche case, but I could see admins adding users, downloading a new csv with the same name and trying to add again.

(Btw why are we leaving the download button unimplemented for now?)

**Review by Oculux314 — APPROVED** [review]
Approved because Aaron's working on a fix in his branch~

**Pull request merged**
