### PR TITLE
414 submitted view

### LINKED ISSUE #414: Exam: Submitted View
### Description:

Create a new view for submitted exams, showing results.*

### Acceptance Criteria:
- [x] Users can access submitted exams from app screen.
- [x] Users can view but not edit submitted exams.
- [x] If graded: display score/max_score on each question.
- [x] If not yet graded: display "awaiting grading" (or similar) where grade would be displayed.
- [x] Interface replaced with grade interface.**
- [x] Dont kick user out if submitted, show grading status instead
- [x] Edit back end to disallow mutations if submitted
- [x] Past exams and submitted exams shown as same category.

### Definition of Done:
- [x] AC met
- [x] Designs on Figma
- [ ] Approved by PM
- [ ] Issue closed

### Notes
\* This is intended to be the way we display grades to the user. If you can think of a better way, talk with Nate!
\** If interface is already implemented. If not, ping Nate to add to backlog.

### PR DESCRIPTION
**Pull request by ardo715**
**Issue**

Exam views didn't have a pre-exam view nor allowed users to review their exams

Closes #414 #432 

**Solution**

Implemented the pre-exam GUI (thanks Eugene)
hooked up front end with back end for pre-exam
users can also now review their quiz.
Did colour correction for answers

This is a huge PR (a lot was done) so there may be some bugs and requires thorough testing
I tried eliminating as many bugs as I could (refreshing, typing in URL etc)
This is very important as we don't want users to be able to change their answers in review mode

**Risks**

no risks

**Reviewers**
@Oculux314 
@johnchen383

### CODE REVIEW

**Review by Oculux314 — CHANGES_REQUESTED** [review]
It looks good! Really like the functionality.

Unfortunately, the extra submit button Sophie added has broken your submitted view functionality by allowing 'resubmitting' haha 
image

Also, if you submit an exam, the app page isn't updated. If you immediately renter that exam, you can 'retake' the quiz, although it automatically sends you to the submit popup and stays there forever.  
I think maybe the app page should send you to different versions of the interface screen based on a server query rather than whatever is happening atm (maybe it's cached again?)

When this is approved, we can merge it then Eugene can make stylistic changes on a new branch I reckon!

Btw is it just this ticket or are these errors just a regular thing??
image

**Comment by Oculux314** [comment]
Also: 🙃 

image

**Review by Oculux314 — APPROVED** [review]
looks good :)

**Review by bcho892 — APPROVED** [review]
LGTM ive made it use localstorage instead as well as removing the use of the answer object

**Pull request merged**
