### PR TITLE
379 general linting

### LINKED ISSUE #379: General: Linting
### Description:

Run the linters and fix all the lint issues.
IMPORTANT: this must be done ASAP after the sprint meeting (before anyone else does work).

### Acceptance Criteria:
- [x] Linting script (with -f) added in root.*
- [x] All linting issues resolved.
- [ ] Entire team notified to pull from main once PR merged to start working.
- [ ] Pre commit hook
- [ ] Bring back Github workflow :))

### Definition of Done:
- [ ] AC met
- [ ] PR linked
- [ ] Branch merged

### Notes
\* Check with John if this is best practice first.

### PR DESCRIPTION
**Pull request by Oculux314**
**Issue**

The codebase has linting issues.

Closes #379

**Solution**

Added linting scripts to root, service, client, and common.
lint displays linting issues.
lint:f displays linting issues and tries to fix them automatically.

Resolved all linting issues picked up by eslint.

**Discussion**

@johnchen383 There's one remaining linting issue I'm scared to address - you authored the commit that last modified it, could you pls have a look? 🙏 
@bcho892 I have no idea how to set up a pre-commit hook or GitHub workflow. I think you raised this in the meeting - could you please show me how it's done and/or set them up yourself?

**Risks**

Should be low-risk - just refactors and I've tested it.
(But I am new to this so have a double-check.)

**Reviewers**

### CODE REVIEW

**Review by bcho892 — APPROVED** [review]

**Comment by johnchen383** [comment]
@Oculux314 done. Won't approve until pre-commit hook and GitHub workflow is integrated tho?

**Review by bcho892 — COMMENTED** [review]
oh right my bad ill see what i can do

**Comment by bcho892** [comment]
I'll keep you in the loop @Oculux314

**Comment by bcho892** [comment]
... no matter what i do it cant find the eslintrc in the common folder (I'm assuming because its not on main), so the workflow wont work. Can we possibly merge this into main then create a separate ticket for the workflow @johnchen383.

**Review by bcho892 — APPROVED** [review]
I've added the pre-commit hook (should be able to install using `yarn`), but see above for issues with workflow

**Comment by Oculux314** [comment]
Thanks, both of you!
I'm hesitant to merge stuff that's failing checks into main (e.g. if someone rolls back changes later on), but I'll make a new branch and reset it to before the workflow stuff to merge in (will send link here).

**Review by johnchen383 — APPROVED** [review]

**Pull request merged**
