### PR TITLE
feat: :sparkles: implement question editor

### LINKED ISSUE #411: Question Editor: Implement
### Description:

Implement the question editor (admin view of exam page).

### Acceptance Criteria:
- [ ] Design matches Figma (group 170).
- [x] Given the user is an admin, upon opening an exam in any way, they see the editor view instead.
- [x] Buttons
  - [x] Submission button is replaced with new question button (and functionality).
  - [x] Exit editor button takes user back to exam management (and loads current exam if possible).
- [x] Description editable and saves upon loss of focus.
- [ ] Image container
  - [ ] Displays uploaded image (or default if no image uploaded).
  - [ ] On click, allows user to upload image.
  - [ ] Clicking (x) deletes image.
- [x] Answer panel
  - [x] Answers editable and saves upon loss of focus.
  - [x] Clicking (x) sets that question as right and all other questions as wrong.
  - [x] Clicking (✓) sets that question as wrong.

### Definition of Done:
- [ ] AC met
- [ ] PR linked
- [ ] Branch merged

### PR DESCRIPTION
**Pull request by bcho892**
**Issue**

Closes #411, #424 

We need a question editor and way for admins to manage the exam. I have created both which function without *major* bugs.

**Solution**

Main functionality 
editor main functionality

As you can see we can:
- Preview the exam questions
- Edit each field
- choose the correct answer

I have also implemented deletion which will be very useful later
deletion

>btw normal exam should still work fine

Users/admins should NOT be able to accidentally access this page as all features are guarded by the url queries as well as the admin check

**Risks**

1. there is **NO upload image field**
- Why? I just thought it would be a pain in the @$5 to get working (need to upload to a file hosting service, download url, update document) and they've been directly pasting the image url using MARKDOWN format so I dont see why they can't do that ( also they wont get some firestore/jdsa0s30804 type url). Also we have the preview option so they can see the image anyway if they're using markdown.
- **Feel free to implement it tho if you want**
2. styling doesn't exactly match figma
- I've used the vuetify components with minimal styling, so I think it'll be a pretty straightforward/good learning experience for someone else to hop on and tune it
3. All this is based on the mutation from the previous team
- Its pretty impressive that most of it worked without me needing to change anything
- Don't think there will be many significant bugs, but most of it will just stem down to error handling
4. >Clicking (✓) sets that question as wrong. doesnt do that
- Can't the admin just click on another (x) ???

**Reviewers**

@Oculux314 
@johnchen383 
@luorixo 
@ardo715 
@nzkevc

### CODE REVIEW

**Review by Oculux314 — CHANGES_REQUESTED** [review]
Wow yet another ✨ amazing ✨ feature you've gone above and beyond on!

Deletion and preview are both great additions.

No image upload is fine - I've tested the markdown image adder and it works (for png at least, gif not supported 😞). Didn't know that was a thing! And dw about not matching the figma exactly - using your initiative is way better! (I'm sure Eugene won't mind too much 😄)

> Clicking (✓) sets that question as wrong. doesnt do that

^ Rationale behind this was I've always found it annoying when a program starts in a state (all answers wrong) and you can change it from this state but can't put it back without doing smth hacky like deleting all the answers and adding them again. But maybe that's just me haha.

## Did some testing:

- Editing a question then previewing it saves the edit to the database but not locally - you need to refresh to see the changes. Editing an answer triggers a refresh from the server, but takes a few seconds - could we perhaps cut out the middleman?
- This should be "add new answer"
image
- Is clicking "add new question" intended to insert the new question before the current one or after? Same for "add new answer".
- Just a general thing - a lot of our operations aren't asynchronous (for both editing and taking exams). We send our changes to the server, wait for the server to respond, then update the local UI/re-enable buttons etc. How hard would it be to have the UI still be responsive while we communicate with the server?
- Danggg the admin can still take exams normally on the app page that's crazy.

That's all I could find from a quick flick through the app. Didn't look at the code.

Also, just realised we have no way to change the order of questions xD  
Problem for a future ticket.

**Comment by bcho892** [comment]
> * Editing a question then previewing it saves the edit to the database but not locally - you need to refresh to see the changes. Editing an answer triggers a refresh from the server, but takes a few seconds - could we perhaps cut out the middleman
fixed 

> * This should be "add new answer"
>   image
ok

> * Is clicking "add new question" intended to insert the new question before the current one or after? Same for "add new answer".

add new question now adds after the last question every time (was random before)

> * Just a general thing - a lot of our operations aren't asynchronous (for both editing and taking exams). We send our changes to the server, wait for the server to respond, then update the local UI/re-enable buttons etc. How hard would it be to have the UI still be responsive while we communicate with the server?

ok done (for the question editor)

also fixed for exam you should see it updates instantly now

> Rationale behind this was I've always found it annoying when a program starts in a state (all answers wrong) and you can change it from this state but can't put it back without doing smth hacky like deleting all the answers and adding them again. But maybe that's just me haha.

ok implemented

> Also, just realised we have no way to change the order of questions xD Problem for a future ticket.

yea shouldnt be too bad but ill leave it for now

**Review by Oculux314 — CHANGES_REQUESTED** [review]
Sorry for more work, but on my device changing questions still doesn't update until you refresh your page :(

Animation

Making changes too fast still messes up with the server calls

too-fast

Otherwise looks great! Tested the add quiz functionality again and it works for new quizzes (but not old quizzes as you said)

**Comment by bcho892** [comment]
@Oculux314 np good job on spotting those cases

**Review by Oculux314 — APPROVED** [review]
No more bugs that I can find.

This is such a beautiful feature!

**Review by ardo715 — APPROVED** [review]
Brilliant work Benson, as per usual.

**Pull request merged**
